//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeLD.DB.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThreeLD.DB.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string EventAddressDisplayName {
            get {
                return ResourceManager.GetString("EventAddressDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address of the event is required..
        /// </summary>
        public static string EventAddressRequired {
            get {
                return ResourceManager.GetString("EventAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string EventCategoryDisplayName {
            get {
                return ResourceManager.GetString("EventCategoryDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category of the event is required..
        /// </summary>
        public static string EventCategoryRequired {
            get {
                return ResourceManager.GetString("EventCategoryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and Time.
        /// </summary>
        public static string EventDateTimeDisplayName {
            get {
                return ResourceManager.GetString("EventDateTimeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date or time is invalid..
        /// </summary>
        public static string EventDateTimeInvalid {
            get {
                return ResourceManager.GetString("EventDateTimeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date and time of the event is required..
        /// </summary>
        public static string EventDateTimeRequired {
            get {
                return ResourceManager.GetString("EventDateTimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string EventDescriptionDisplayName {
            get {
                return ResourceManager.GetString("EventDescriptionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description of the event is required..
        /// </summary>
        public static string EventDescriptionRequired {
            get {
                return ResourceManager.GetString("EventDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string EventDurationDisplayName {
            get {
                return ResourceManager.GetString("EventDurationDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The duration is invalid..
        /// </summary>
        public static string EventDurationInvalid {
            get {
                return ResourceManager.GetString("EventDurationInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The duration of the event is required..
        /// </summary>
        public static string EventDurationRequired {
            get {
                return ResourceManager.GetString("EventDurationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string EventNameDisplayName {
            get {
                return ResourceManager.GetString("EventNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the event is required..
        /// </summary>
        public static string EventNameRequired {
            get {
                return ResourceManager.GetString("EventNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string EventUrlDisplayName {
            get {
                return ResourceManager.GetString("EventUrlDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL is invalid..
        /// </summary>
        public static string EventUrlInvalid {
            get {
                return ResourceManager.GetString("EventUrlInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string NotificationMessageDisplayName {
            get {
                return ResourceManager.GetString("NotificationMessageDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message of the notication is required..
        /// </summary>
        public static string NotificationMessageRequired {
            get {
                return ResourceManager.GetString("NotificationMessageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string PreferenceCategoryDisplayName {
            get {
                return ResourceManager.GetString("PreferenceCategoryDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category of the preference is required..
        /// </summary>
        public static string PreferenceCategoryRequired {
            get {
                return ResourceManager.GetString("PreferenceCategoryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string UserFirstNameDisplayName {
            get {
                return ResourceManager.GetString("UserFirstNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first name is required..
        /// </summary>
        public static string UserFirstNameRequired {
            get {
                return ResourceManager.GetString("UserFirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string UserLastNameDisplayName {
            get {
                return ResourceManager.GetString("UserLastNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last name is required..
        /// </summary>
        public static string UserLastNameRequired {
            get {
                return ResourceManager.GetString("UserLastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserUserNameDisplayName {
            get {
                return ResourceManager.GetString("UserUserNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name is required..
        /// </summary>
        public static string UserUserNameRequired {
            get {
                return ResourceManager.GetString("UserUserNameRequired", resourceCulture);
            }
        }
    }
}
