//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeLD.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThreeLD.Web.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string ActionsText {
            get {
                return ResourceManager.GetString("ActionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You prefer every category out there..
        /// </summary>
        public static string AllPreferencesText {
            get {
                return ResourceManager.GetString("AllPreferencesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Editor.
        /// </summary>
        public static string AssignEditorText {
            get {
                return ResourceManager.GetString("AssignEditorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark on event {0} doesn&apos;t exist..
        /// </summary>
        public static string BookmarkDoesNotExistFormat {
            get {
                return ResourceManager.GetString("BookmarkDoesNotExistFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark on event {0} has been removed..
        /// </summary>
        public static string BookmarkRemovedFormat {
            get {
                return ResourceManager.GetString("BookmarkRemovedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmarks.
        /// </summary>
        public static string BookmarksHeader {
            get {
                return ResourceManager.GetString("BookmarksHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark.
        /// </summary>
        public static string BookmarkText {
            get {
                return ResourceManager.GetString("BookmarkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category {0} is already assigned as preferred..
        /// </summary>
        public static string CategoryAlreadyPreferredFormat {
            get {
                return ResourceManager.GetString("CategoryAlreadyPreferredFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the category..
        /// </summary>
        public static string ChooseCategory {
            get {
                return ResourceManager.GetString("ChooseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose category....
        /// </summary>
        public static string ChooseCategoryText {
            get {
                return ResourceManager.GetString("ChooseCategoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an Event.
        /// </summary>
        public static string CreateEventText {
            get {
                return ResourceManager.GetString("CreateEventText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateText {
            get {
                return ResourceManager.GetString("CreateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} an Event.
        /// </summary>
        public static string EditEventHeaderFormat {
            get {
                return ResourceManager.GetString("EditEventHeaderFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} an Event.
        /// </summary>
        public static string EditEventTitleFormat {
            get {
                return ResourceManager.GetString("EditEventTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditText {
            get {
                return ResourceManager.GetString("EditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please try again..
        /// </summary>
        public static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has already been bookmarked..
        /// </summary>
        public static string EventAlreadyBookmarkedFormat {
            get {
                return ResourceManager.GetString("EventAlreadyBookmarkedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been approved..
        /// </summary>
        public static string EventApprovedFormat {
            get {
                return ResourceManager.GetString("EventApprovedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been bookmarked..
        /// </summary>
        public static string EventBookmarkedFormat {
            get {
                return ResourceManager.GetString("EventBookmarkedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been created..
        /// </summary>
        public static string EventCreatedFormat {
            get {
                return ResourceManager.GetString("EventCreatedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been deleted..
        /// </summary>
        public static string EventDeletedFormat {
            get {
                return ResourceManager.GetString("EventDeletedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified event doesn&apos;t exist..
        /// </summary>
        public static string EventDoesNotExist {
            get {
                return ResourceManager.GetString("EventDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been updated..
        /// </summary>
        public static string EventUpdatedFormat {
            get {
                return ResourceManager.GetString("EventUpdatedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string LinkText {
            get {
                return ResourceManager.GetString("LinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid name or password..
        /// </summary>
        public static string LoginInvalid {
            get {
                return ResourceManager.GetString("LoginInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LoginPasswordDisplayName {
            get {
                return ResourceManager.GetString("LoginPasswordDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is required..
        /// </summary>
        public static string LoginPasswordRequired {
            get {
                return ResourceManager.GetString("LoginPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LogInText {
            get {
                return ResourceManager.GetString("LogInText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string LoginUserNameDisplayName {
            get {
                return ResourceManager.GetString("LoginUserNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name is required..
        /// </summary>
        public static string LoginUserNameRequired {
            get {
                return ResourceManager.GetString("LoginUserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string LogOutText {
            get {
                return ResourceManager.GetString("LogOutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Notifications.
        /// </summary>
        public static string MyNotificationsText {
            get {
                return ResourceManager.GetString("MyNotificationsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string MyProfileText {
            get {
                return ResourceManager.GetString("MyProfileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any bookmarks..
        /// </summary>
        public static string NoBookmarks {
            get {
                return ResourceManager.GetString("NoBookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any preferences..
        /// </summary>
        public static string NoPreferencesText {
            get {
                return ResourceManager.GetString("NoPreferencesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The notification is already checked as read..
        /// </summary>
        public static string NotificationAlreadyRead {
            get {
                return ResourceManager.GetString("NotificationAlreadyRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The notification doesn&apos;t exist..
        /// </summary>
        public static string NotificationDoesNotExist {
            get {
                return ResourceManager.GetString("NotificationDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The notification has been checked as read..
        /// </summary>
        public static string NotificationRead {
            get {
                return ResourceManager.GetString("NotificationRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check all as read.
        /// </summary>
        public static string NotificationsCheckAll {
            get {
                return ResourceManager.GetString("NotificationsCheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No User Accounts.
        /// </summary>
        public static string NoUserAccountsText {
            get {
                return ResourceManager.GetString("NoUserAccountsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OKText {
            get {
                return ResourceManager.GetString("OKText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The preference has been added..
        /// </summary>
        public static string PreferenceAdded {
            get {
                return ResourceManager.GetString("PreferenceAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified preference doesn&apos;t exist..
        /// </summary>
        public static string PreferenceDoesNotExist {
            get {
                return ResourceManager.GetString("PreferenceDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The preference has been removed..
        /// </summary>
        public static string PreferenceRemoved {
            get {
                return ResourceManager.GetString("PreferenceRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string PreferencesHeader {
            get {
                return ResourceManager.GetString("PreferencesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string ProfileHeader {
            get {
                return ResourceManager.GetString("ProfileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Info.
        /// </summary>
        public static string ProfileTitle {
            get {
                return ResourceManager.GetString("ProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposed Events.
        /// </summary>
        public static string ProposedEventsHeader {
            get {
                return ResourceManager.GetString("ProposedEventsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposed Events.
        /// </summary>
        public static string ProposedEventsTitle {
            get {
                return ResourceManager.GetString("ProposedEventsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propose an Event.
        /// </summary>
        public static string ProposeEventText {
            get {
                return ResourceManager.GetString("ProposeEventText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propose.
        /// </summary>
        public static string ProposeText {
            get {
                return ResourceManager.GetString("ProposeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string SignUpEmailDisplayName {
            get {
                return ResourceManager.GetString("SignUpEmailDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is invalid..
        /// </summary>
        public static string SignUpEmailInvalid {
            get {
                return ResourceManager.GetString("SignUpEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is required..
        /// </summary>
        public static string SignUpEmailRequired {
            get {
                return ResourceManager.GetString("SignUpEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string SignUpFirstNameDisplayName {
            get {
                return ResourceManager.GetString("SignUpFirstNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first name is required..
        /// </summary>
        public static string SignUpFirstNameRequired {
            get {
                return ResourceManager.GetString("SignUpFirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string SignUpLastNameDisplayName {
            get {
                return ResourceManager.GetString("SignUpLastNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last name is required..
        /// </summary>
        public static string SignUpLastNameRequired {
            get {
                return ResourceManager.GetString("SignUpLastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string SignUpPasswordDisplayName {
            get {
                return ResourceManager.GetString("SignUpPasswordDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is required..
        /// </summary>
        public static string SignUpPasswordRequired {
            get {
                return ResourceManager.GetString("SignUpPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string SignUpText {
            get {
                return ResourceManager.GetString("SignUpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string SignUpUserNameDisplayName {
            get {
                return ResourceManager.GetString("SignUpUserNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name is required..
        /// </summary>
        public static string SignUpUserNameRequired {
            get {
                return ResourceManager.GetString("SignUpUserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string SubmitText {
            get {
                return ResourceManager.GetString("SubmitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unassign Editor.
        /// </summary>
        public static string UnassignEditorText {
            get {
                return ResourceManager.GetString("UnassignEditorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Not Found.
        /// </summary>
        public static string UserNotFoundText {
            get {
                return ResourceManager.GetString("UserNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Accounts.
        /// </summary>
        public static string UsersHeader {
            get {
                return ResourceManager.GetString("UsersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string UsersTitle {
            get {
                return ResourceManager.GetString("UsersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string ViewEventsHeader {
            get {
                return ResourceManager.GetString("ViewEventsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Events.
        /// </summary>
        public static string ViewEventsTitle {
            get {
                return ResourceManager.GetString("ViewEventsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Notifications.
        /// </summary>
        public static string ViewNotificationsHeader {
            get {
                return ResourceManager.GetString("ViewNotificationsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Notifications.
        /// </summary>
        public static string ViewNotificationsTitle {
            get {
                return ResourceManager.GetString("ViewNotificationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefered Events.
        /// </summary>
        public static string ViewPreferedEventsHeader {
            get {
                return ResourceManager.GetString("ViewPreferedEventsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefered Events.
        /// </summary>
        public static string ViewPreferedEventsTitle {
            get {
                return ResourceManager.GetString("ViewPreferedEventsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Preferred Events.
        /// </summary>
        public static string ViewPreferredEventsText {
            get {
                return ResourceManager.GetString("ViewPreferredEventsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Proposed Events.
        /// </summary>
        public static string ViewProposedEventsText {
            get {
                return ResourceManager.GetString("ViewProposedEventsText", resourceCulture);
            }
        }
    }
}
